import {BUILD_VERSION} from '../../src/buildVersion.js';
import {test,expect} from '@playwright/test';
import {DECK_FACES,type RoomView} from '../../shared/rules.js';

function fixture():RoomView{
 const players=Array.from({length:4},(_,i)=>({id:`player-${i}`,name:`게스트 ${1000+i}`,avatar:['pronoun','verb','adjective','count'][i] as 'pronoun'|'verb'|'adjective'|'count',rating:1000,ratingDelta:0,points:0,reward:0,score:i*3,ready:true,connected:true,handCount:5,handPreview:DECK_FACES.slice(i*5,i*5+5).map((c,j)=>({...c,id:`preview-${i}-${j}`})),draftPreview:DECK_FACES.slice(i*5,i*5+1).map((c,j)=>({...c,id:`draft-${i}-${j}`})),playedSentences:[DECK_FACES.slice(i*5,i*5+2).map((c,j)=>({...c,id:`played-${i}-${j}`}))],rematch:false,ai:false}));
 return {code:'123456',phase:'battle',matchId:'landscape-fixture',players,you:players[0].id,hand:DECK_FACES.slice(0,5).map((c,i)=>({...c,id:`landscape-${i}`})),handVersion:1,endsAt:0,stageEndsAt:0,nextDealAt:0,dealSerial:1,deckCount:19,deckTotal:39,usedCards:[],dealIntervalMs:0,goCount:0,multiplier:1,highScore:0,serverNow:Date.now(),actionAt:0,exchangeAt:0,reconnectMs:30000,durationMs:0,log:[],expiresAt:0};
}
for(const size of [{width:667,height:320},{width:844,height:390},{width:932,height:430},{width:1024,height:768},{width:1920,height:1080}])test(`mobile landscape ${size.width}x${size.height}: board and hand fit, fullscreen can be tested`,async({browser})=>{
 const context=await browser.newContext({viewport:size,isMobile:true,hasTouch:true,deviceScaleFactor:2});const page=await context.newPage();const room=fixture(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.routeWebSocket('**/socket',ws=>{ws.onMessage(()=>{ws.send(JSON.stringify({type:'session',token:'landscape-fixture',name:'게스트 1000',avatar:'pronoun',rating:1000,points:0}));ws.send(JSON.stringify({type:'state',room}));});});
  await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('.battle')).toBeVisible();await expect(page.locator('.table-player')).toHaveCount(4);await expect(page.locator('.hand .game-card')).toHaveCount(5);
  await expect(page.getByRole('button',{name:'설정 열기'})).toBeVisible();await expect(page.locator('.game-settings')).toHaveCount(0); 
  const geometry=await page.evaluate(()=>{const rect=(selector:string)=>{const b=document.querySelector(selector)!.getBoundingClientRect();return{top:b.top,bottom:b.bottom,left:b.left,right:b.right};};return{width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,score:rect('.table-scoreboard'),field:rect('.sentence-area'),hand:rect('.hand .game-card'),fullscreen:rect('.settings-trigger')};});
  if(size.height<=900)expect(geometry.score.top).toBeGreaterThanOrEqual(8);expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.width+2);expect(geometry.scrollHeight).toBeLessThanOrEqual(geometry.height+2);
  for(const item of [geometry.score,geometry.field,geometry.hand,geometry.fullscreen]){expect(item.top).toBeGreaterThanOrEqual(-2);expect(item.bottom).toBeLessThanOrEqual(geometry.height+2);expect(item.right).toBeLessThanOrEqual(geometry.width+2);}
  await page.screenshot({path:`docs/screenshots/landscape-${size.width}.png`});
  await expect(page.locator('.table-player:not(.self) .mini-hand-preview .status-card-block').first()).toBeVisible();await expect(page.locator('.table-player').nth(1).locator('.status-card-block')).toHaveCount(8);
  await page.getByRole('button',{name:'게스트 1001의 손패와 문장 보기'}).tap();await expect(page.locator('.opponent-field-preview .opponent-preview-group')).toHaveCount(3);await expect(page.locator('.opponent-preview-group').filter({hasText:'현재 문장'}).locator('img')).toHaveCount(1);await expect(page.locator('.hand[aria-label="내 손패"] .game-card')).toHaveCount(5);
  await page.getByRole('button',{name:'상대 미리보기 닫기'}).tap();await expect(page.locator('.sentence-area')).toBeVisible();await page.getByRole('button',{name:'게스트 1001의 손패와 문장 보기'}).tap();await page.getByRole('button',{name:'내 프로필 · 내 문장 보기'}).tap();await expect(page.locator('.sentence-area')).toBeVisible();
  await page.getByRole('button',{name:'감정표현 열기'}).tap();await expect(page.locator('.emoji-options button')).toHaveCount(4);await page.getByRole('button',{name:'감정표현 열기'}).tap();
  const first=page.locator('.hand .game-card').first();const point=await first.evaluate(el=>{const r=el.getBoundingClientRect();for(let y=r.top+12;y<r.bottom-12;y+=6)for(let x=r.left+12;x<r.right-12;x+=6)if(document.elementFromPoint(x,y)?.closest('button')===el)return{x,y};return null;});expect(point).not.toBeNull();await page.touchscreen.tap(point!.x,point!.y);await expect(page.locator('.sentence-card')).toHaveCount(1);await expect(page.locator('.hand .game-card')).toHaveCount(4);await page.locator('.sentence-card').tap();await expect(page.locator('.hand .game-card')).toHaveCount(5);
  const beforeSettings=await page.locator('.battle').boundingBox();const beforeField=await page.locator('.sentence-area').boundingBox();const beforeHand=await page.locator('.hand-container').boundingBox();await page.getByRole('button',{name:'설정 열기'}).tap();await expect(page.getByRole('dialog',{name:'게임 설정'})).toBeVisible();expect(await page.locator('.battle').boundingBox()).toEqual(beforeSettings);expect(await page.locator('.sentence-area').boundingBox()).toEqual(beforeField);expect(await page.locator('.hand-container').boundingBox()).toEqual(beforeHand);const popup=(await page.locator('.game-settings').boundingBox())!;expect(Math.abs(popup.x+popup.width/2-size.width/2)).toBeLessThan(2);expect(Math.abs(popup.y+popup.height/2-size.height/2)).toBeLessThan(2);expect(await page.locator('.game-settings .toolbar-action').first().evaluate(e=>getComputedStyle(e).textAlign)).toBe('center');await expect(page.getByRole('button',{name:'카드 확대 보기'})).toBeVisible();await page.screenshot({path:'docs/screenshots/settings-'+size.width+'.png'});await page.getByRole('button',{name:'전체화면'}).tap();await expect.poll(async()=>await page.evaluate(()=>Boolean(document.fullscreenElement)||Boolean(document.querySelector('.toast')))).toBe(true);
  if(await page.evaluate(()=>Boolean(document.fullscreenElement))){await expect(page.getByRole('button',{name:'전체화면 종료'})).toBeVisible();await page.getByRole('button',{name:'전체화면 종료'}).tap();await expect(page.getByRole('button',{name:'전체화면'})).toBeVisible();}
  await page.getByRole('button',{name:'설정 닫기'}).tap();await expect(page.locator('.game-settings')).toHaveCount(0);expect(errors).toEqual([]);
 }finally{await context.close();}
});


for(const size of [{width:667,height:320},{width:844,height:390},{width:932,height:430}])test(`landscape all screens ${size.width}x${size.height}: home, match, result, consent and dialogs`,async({browser})=>{
 const context=await browser.newContext({viewport:size,isMobile:true,hasTouch:true,deviceScaleFactor:2});const page=await context.newPage();let push:(r:RoomView|null)=>void=()=>{};const messages:any[]=[];
 const room=fixture();room.dealSerial=0;
 await page.routeWebSocket('**/socket',ws=>{push=r=>ws.send(JSON.stringify({type:'state',room:r}));ws.onMessage(raw=>{const m=JSON.parse(String(raw));messages.push(m);if(m.type==='hello'){ws.send(JSON.stringify({type:'session',token:'screens-fixture',name:'게스트 1000',avatar:'pronoun',rating:1000,points:0}));push(null);}else if(m.type==='inspectRob')ws.send(JSON.stringify({type:'robView',matchId:room.matchId,cardId:m.cardId,players:[{...room.players[1],handVersion:1,fieldVersion:1,cards:DECK_FACES.slice(0,30).map((c,i)=>({...c,id:'rob-'+i,source:'hand'}))}]}));else if(m.type==='inspectExchange')ws.send(JSON.stringify({type:'exchangeView',matchId:room.matchId,cardId:m.cardId,players:[{...room.players[1],handVersion:1,cards:DECK_FACES.slice(0,30).map((c,i)=>({...c,id:'exchange-'+i}))}]}));})});
 const fits=async(selectors:string[])=>{const g=await page.evaluate(selectors=>({w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,rects:selectors.map(s=>{const r=document.querySelector(s)!.getBoundingClientRect();return {s,t:r.top,b:r.bottom,l:r.left,r:r.right}})}),selectors);expect(g.sw).toBeLessThanOrEqual(g.w+1);expect(g.sh).toBeLessThanOrEqual(g.h+1);for(const r of g.rects){expect(r.t,r.s).toBeGreaterThanOrEqual(0);expect(r.b,r.s).toBeLessThanOrEqual(g.h+1);expect(r.l,r.s).toBeGreaterThanOrEqual(0);expect(r.r,r.s).toBeLessThanOrEqual(g.w+1)}};
 try{
  await page.goto('/');await expect(page.locator('.quick-start')).toBeEnabled();await fits(['.quick-start','.home-profile','.quick-rules']);expect(await page.locator('.quick-start').evaluate(el=>{const r=el.getBoundingClientRect();return Math.abs(r.left+r.width/2-innerWidth/2)})).toBeLessThan(2);
  for(const phase of ['matching','reveal','dealing'] as const){room.phase=phase;room.stageEndsAt=Date.now()+5000;push(room);await expect(page.locator(phase==='dealing'?'.battle':'.match-screen')).toBeVisible();await fits(phase==='matching'?['.matching-slots','.match-screen>.text-button']:phase==='reveal'?['.versus-layout','.versus-screen>p']:['.sentence-actions','.emoji-trigger']);}
  room.phase='battle';room.drawVote={id:'consent',approved:[]};room.nextDealAt=Date.now()+40000;room.dealIntervalMs=40000;push(room);
  const approve=page.getByRole('button',{name:'카드 배분 동의',exact:true});await expect(approve).toHaveClass(/awaiting-consent/);await expect(approve).not.toHaveClass(/last-consent/);room.drawVote.approved=room.players.filter(p=>p.id!==room.you).map(p=>p.id);push(room);await expect(approve).toHaveClass(/last-consent/);expect(await approve.evaluate(el=>getComputedStyle(el).animationName)).toBe('none');await expect(page.locator('.draw-vote-panel')).toHaveCount(0);await approve.tap();await expect.poll(()=>messages.some(m=>m.type==='drawVote'&&m.approve===true)).toBe(true);
  room.drawVote.approved=[room.you];push(room);await expect(page.getByRole('button',{name:'카드 배분 동의 완료'})).not.toHaveClass(/awaiting-consent|last-consent/);
  await page.getByRole('button',{name:'감정표현 열기'}).tap();await fits(['.emoji-trigger','.emoji-options']);await page.getByRole('button',{name:'감정표현 열기'}).tap();
  room.hand=DECK_FACES.map((c,i)=>({...c,id:'many-'+i}));room.handVersion++;push(room);await expect(page.locator('.hand .game-card')).toHaveCount(39);
  await expect.poll(()=>page.evaluate(()=>{const bottom=Math.max(...[...document.querySelectorAll('.hand .game-card')].map(c=>c.getBoundingClientRect().bottom));return document.querySelector('.emoji-trigger')!.getBoundingClientRect().top-bottom;})).toBeGreaterThanOrEqual(0);
  room.decision={id:'go',playerId:room.you,startedAt:Date.now(),expiresAt:0};room.highScore=24;push(room);await expect(page.locator('.go-dialog')).toBeVisible();await fits(['.go-dialog','.go-actions']);delete room.decision;
  room.exchange={id:'ex',fromId:'player-1',toId:room.you,expiresAt:Date.now()+20000,offer:room.hand[0],wanted:room.hand[1]};push(room);await expect(page.locator('.exchange-quick-replies')).toBeVisible();await fits(['.special-dialog','.exchange-quick-replies','.special-actions']);delete room.exchange;
  room.hand=[{id:'rob-check',kind:'rob'},{id:'exchange-check',kind:'exchange'},...room.hand];room.handVersion++;push(room);
  await page.getByRole('button',{name:'손패 펼쳐 보기'}).tap();await page.locator('[data-card-id="rob-check"]').tap();await expect(page.locator('.rob-card-choice')).toHaveCount(30);expect(await page.locator('.rob-card-choice').first().evaluate(e=>e.clientWidth)).toBeGreaterThanOrEqual(80);await page.screenshot({path:`docs/screenshots/mobile-rob-${size.width}.png`});await fits(['.rob-dialog','.rob-dialog .special-actions']);await page.getByRole('button',{name:'취소',exact:true}).tap();
  await page.locator('[data-card-id="exchange-check"]').tap();await expect(page.locator('.exchange-player')).toHaveCount(1);expect(await page.locator('.exchange-player .exchange-cards button').first().evaluate(e=>e.clientWidth)).toBeGreaterThanOrEqual(76);await page.screenshot({path:`docs/screenshots/mobile-exchange-${size.width}.png`});await fits(['.exchange-dialog','.exchange-dialog .special-actions']);await page.getByRole('button',{name:'취소',exact:true}).tap();
  room.phase='result';room.winner=room.you;room.reason='스톱을 선택했습니다.';push(room);await expect(page.locator('.result')).toBeVisible();await fits(['.result-scores','.result>.primary','.result>.text-button']);await page.screenshot({path:`docs/screenshots/landscape-result-${size.width}.png`});
 }finally{await context.close()}
});




test('desktop table fills middle, hand hugs bottom and return is only an icon',async({browser})=>{
 const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage(),room=fixture();
 await page.routeWebSocket('**/socket',ws=>ws.onMessage(()=>{ws.send(JSON.stringify({type:'session',token:'desktop-layout',name:'게스트 1000',avatar:'pronoun',rating:1000,points:0}));ws.send(JSON.stringify({type:'state',room}));}));
 try{
  await page.goto('/');await expect(page.locator('.battle')).toBeVisible();await expect(page.locator('.hand .game-card')).toHaveCount(5);
  const geometry=await page.evaluate(()=>{const b=(s:string)=>document.querySelector(s)!.getBoundingClientRect();return{height:innerHeight,scroll:document.documentElement.scrollHeight,field:b('.sentence-area').toJSON(),hand:b('.battle-hand-zone').toJSON(),cardsBottom:Math.max(...[...document.querySelectorAll('.hand .game-card')].map(c=>c.getBoundingClientRect().bottom)),emojiTop:b('.emoji-trigger').top,settings: getComputedStyle(document.querySelector('.settings-trigger')!).position}});
  expect(geometry.scroll).toBe(geometry.height);expect(geometry.field.height).toBeGreaterThan(geometry.height*.3);expect(geometry.hand.bottom).toBe(geometry.height);expect(geometry.field.bottom).toBeLessThan(geometry.hand.top);await expect(page.locator('.build-version')).toHaveText(BUILD_VERSION);expect(geometry.emojiTop-geometry.cardsBottom).toBeGreaterThanOrEqual(0);expect(geometry.emojiTop-geometry.cardsBottom).toBeLessThanOrEqual(8);expect(geometry.settings).toBe('fixed');
  const back=page.getByRole('button',{name:'모두 되돌리기'});await expect(back).toHaveText('');await expect(back.locator('svg')).toHaveCount(1);
  await page.getByRole('button',{name:'손패 펼쳐 보기'}).click();await page.locator('.hand .game-card').first().click();await expect(page.locator('.sentence-card')).toHaveCount(1);await back.click();await expect(page.locator('.sentence-card')).toHaveCount(0);await expect(page.locator('.hand .game-card')).toHaveCount(5);
  await page.getByRole('button',{name:'손패 모아 보기'}).click();await page.screenshot({path:'docs/screenshots/desktop-table-1366.png'});
 }finally{await context.close()}
});


