import {test,expect} from '@playwright/test';
import {DECK_FACES,type RoomView} from '../../shared/rules.js';
for(const supported of [true,false])test(`mobile quick start requests fullscreen and landscape; ROB victim panel (${supported?'supported':'unsupported'})`,async({browser})=>{
 const ctx=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const page=await ctx.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript((supported)=>{const calls:string[]=[];(window as any).displayCalls=calls;Object.defineProperty(HTMLElement.prototype,'requestFullscreen',{value:()=>{calls.push('fullscreen');return supported?Promise.resolve():Promise.reject(Error('unsupported'))}});Object.defineProperty(screen.orientation,'lock',{value:(direction:string)=>{calls.push(direction);return supported?Promise.resolve():Promise.reject(Error('unsupported'))}});},supported);
 const room:RoomView={code:'123456',phase:'battle',matchId:'display-fixture',players:[{id:'me',name:'내 게스트',avatar:'pronoun',rating:1000,ratingDelta:0,points:0,reward:0,score:0,ready:true,connected:true,handCount:5,rematch:false,ai:false},{id:'rival',name:'상대 게스트',avatar:'verb',rating:1000,ratingDelta:0,points:0,reward:0,score:0,ready:true,connected:true,handCount:5,rematch:false,ai:false}],you:'me',hand:DECK_FACES.slice(0,5).map((c,i)=>({...c,id:'card-'+i})),handVersion:1,endsAt:0,stageEndsAt:0,nextDealAt:0,dealSerial:0,deckCount:29,deckTotal:39,usedCards:[],dealIntervalMs:0,goCount:0,multiplier:1,highScore:0,serverNow:Date.now(),actionAt:0,exchangeAt:0,reconnectMs:30000,durationMs:0,log:[],expiresAt:0};
 let push:()=>void=()=>{};const messages:any[]=[];
 await page.routeWebSocket('**/socket',ws=>{push=()=>ws.send(JSON.stringify({type:'state',room}));ws.onMessage(raw=>{const m=JSON.parse(String(raw));messages.push(m);if(m.type==='hello')ws.send(JSON.stringify({type:'session',token:'display',name:'게스트 1000',avatar:'pronoun',rating:1000,points:0}));if(m.type==='quick')push();if(m.type==='robNoticeRead'){room.robNotices=room.robNotices?.filter(n=>n.id!==m.noticeId);push();}})});
 try{
  await page.goto('/');await page.getByRole('button',{name:'빠른시작'}).tap({timeout:45000});await expect(page.locator('.battle')).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).displayCalls)).toEqual(['fullscreen','landscape']);expect(messages.some(m=>m.type==='quick')).toBe(true);
  room.robNotices=[{id:'victim-event',fromId:'rival',fromName:'상대 게스트',fromAvatar:'verb',card:{...DECK_FACES.find(c=>c.kind==='verb')!,id:'stolen'},source:'field'}];push();
  const panel=page.getByRole('dialog',{name:'ROB 피해 알림'});await expect(panel).toBeVisible();await expect(panel).toContainText('상대 게스트');await expect(panel).toContainText('필드');await expect(panel).toContainText('일반동사');await expect(panel.locator('.illustration')).toBeVisible();const rect=(await panel.boundingBox())!;expect(rect.y).toBeGreaterThanOrEqual(0);expect(rect.y+rect.height).toBeLessThanOrEqual(390);await page.screenshot({path:'docs/screenshots/mobile-rob-victim.png'});
  await panel.getByRole('button',{name:'확인',exact:true}).tap();await expect(panel).toHaveCount(0);expect(messages.some(m=>m.type==='robNoticeRead'&&m.noticeId==='victim-event'&&m.matchId===room.matchId)).toBe(true);expect(errors).toEqual([]);
 }finally{await ctx.close()}
});

