import {BUILD_VERSION} from '../../src/buildVersion.js';
import {test,expect} from '@playwright/test';
import {DECK_FACES,type RoomView} from '../../shared/rules.js';
for(const reducedViewport of [false,true])test(`${BUILD_VERSION} phone stage ${reducedViewport?'with status/navigation bars':'normal'}: centered field and separate hand`,async({browser})=>{
 const size={width:932,height:430};const context=await browser.newContext({viewport:size,isMobile:true,hasTouch:true,deviceScaleFactor:2.5}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 if(reducedViewport)await page.addInitScript(()=>{const v=Object.assign(new EventTarget(),{width:932,height:384,offsetTop:18,offsetLeft:0});Object.defineProperty(window,'visualViewport',{configurable:true,value:v});(window as any).__phoneViewport=v;});
 const hand=['pronoun','verb','adjective','be','get3','protect','rob','count'].map((kind,i)=>({...DECK_FACES.find(c=>c.kind===kind)!,id:'phone-'+i}));
 const player={id:'me',name:'게스트 5159',avatar:'pronoun' as const,lastAction:{id:'message',text:'게스트 5159 님의 답장 · 명사 필요 · 카드 교환을 요청했어요.'},rating:1000,ratingDelta:0,points:0,reward:0,score:0,ready:true,connected:true,handCount:8,handPreview:hand,rematch:false,ai:false};
 const room:RoomView={code:'123456',phase:'battle',matchId:'phone-v09',players:[player,{...player,id:'ai',name:'로고스 AI',ai:true,avatar:'count'}],you:'me',hand,handVersion:1,endsAt:0,stageEndsAt:0,nextDealAt:Date.now()+30000,dealSerial:1,deckCount:23,deckTotal:39,usedCards:[],dealIntervalMs:30000,goCount:0,multiplier:1,highScore:0,serverNow:Date.now(),actionAt:0,exchangeAt:0,reconnectMs:30000,durationMs:0,log:[],expiresAt:0,drawVote:{id:'phone-vote',approved:['ai']}};
 if(reducedViewport)await page.route('**/profiles/pronoun.png*',route=>route.fulfill({status:404,body:''}));const sent:any[]=[];await page.routeWebSocket('**/socket',ws=>ws.onMessage(raw=>{const m=JSON.parse(String(raw));sent.push(m);if(m.type==='hello'){ws.send(JSON.stringify({type:'session',token:'phone-v09',name:player.name,avatar:player.avatar,rating:1000,points:0}));ws.send(JSON.stringify({type:'state',room}));}if(m.type==='drawVote'){room.drawVote!.approved.push('me');ws.send(JSON.stringify({type:'state',room}));}}));
 try{
  await page.goto('/');await expect(page.locator('.battle')).toBeVisible({timeout:45000});await expect(page.locator('.build-version')).toHaveText(BUILD_VERSION);
  const measure=()=>page.evaluate(()=>{const b=(s:string)=>document.querySelector(s)!.getBoundingClientRect();const field=b('.sentence-area'),hud=b('.table-feedback-row'),hand=b('.battle-hand-zone'),submit=b('.submit'),undo=b('.return-all-icon'),shell=b('.shell'),empty=document.querySelector('.empty-sentence')?.getBoundingClientRect();return{h:innerHeight,scroll:document.documentElement.scrollHeight,field:field.toJSON(),hud:hud.toJSON(),hand:hand.toJSON(),submit:submit.toJSON(),undo:undo.toJSON(),shell:shell.toJSON(),empty:empty?.toJSON()}});
  const balloon=page.locator('.table-player.self>.player-last-action');await expect(balloon).toBeVisible();const bubble=await balloon.boundingBox();expect(bubble!.y).toBeGreaterThanOrEqual(reducedViewport?18:0);expect(await balloon.evaluate(e=>getComputedStyle(e).whiteSpace)).toBe('normal');const avatar=page.locator('.table-player.self .character-avatar');await expect(avatar).toBeVisible();if(reducedViewport)await expect(avatar.locator('img')).toHaveCount(0);else await expect.poll(()=>avatar.locator('img').evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);const g=await measure();expect(g.scroll).toBeLessThanOrEqual(g.h);expect(g.field.bottom).toBeLessThan(g.hand.top);expect(g.hud.bottom).toBeLessThan(g.field.top);expect(g.field.right-g.submit.right).toBeLessThan(10);expect(g.field.bottom-g.submit.bottom).toBeLessThan(12);expect(Math.abs(g.empty.x+g.empty.width/2-g.field.x-g.field.width/2)).toBeLessThan(1);expect(g.undo.x-g.field.x).toBeLessThan(10);expect(g.undo.y-g.field.y).toBeLessThan(10);
  if(reducedViewport){expect(g.shell.top).toBe(18);expect(g.shell.height).toBe(384);expect(g.hand.bottom).toBeLessThanOrEqual(402)}else expect(g.hand.bottom).toBe(430);
  const approve=page.getByRole('button',{name:'카드 배분 동의',exact:true});await expect(approve).toHaveClass(/last-consent/);await expect(approve).not.toContainText('동의 하기');await expect(approve).not.toContainText('동의 대기');await expect(approve.locator('.deck-request-caption')).toHaveText(/카드 요청 \d+s/);expect(await approve.evaluate(e=>getComputedStyle(e).flexDirection)).toBe('column');await expect(approve).toContainText('카드 요청');expect(await approve.evaluate(e=>getComputedStyle(e).animationName)).toBe('none');const progress=page.getByRole('progressbar',{name:'자동 카드 배분까지'});await expect(progress).toHaveAttribute('aria-valuemax','100');await approve.tap();await expect.poll(()=>sent.some(m=>m.type==='drawVote'&&m.approve)).toBe(true);await expect(page.getByRole('button',{name:'카드 배분 동의 완료'})).toBeVisible();
  await page.getByRole('button',{name:'손패 펼쳐 보기'}).tap();for(let i=0;i<3;i++)await page.locator(`[data-card-id="phone-${i}"]`).tap();const center=await page.locator('.sentence-card').evaluateAll(els=>{const boxes=els.map(e=>e.getBoundingClientRect()),f=document.querySelector('.sentence-area')!.getBoundingClientRect();return Math.abs((Math.min(...boxes.map(b=>b.left))+Math.max(...boxes.map(b=>b.right)))/2-f.left-f.width/2)});expect(center).toBeLessThan(1);const card=await page.locator('.sentence-card').first().boundingBox();expect(card!.height).toBeGreaterThan(g.field.height-20);expect(await page.locator('.sentence-card .illustration').first().evaluate(e=>getComputedStyle(e).borderRadius)).toBe('3px');await page.getByRole('button',{name:'손패 모아 보기'}).tap();
  await page.screenshot({path:`docs/screenshots/v0903-phone-${reducedViewport?'system-bars':'normal'}.png`});
  if(reducedViewport){await page.evaluate(()=>{const v=(window as any).__phoneViewport;v.height=400;v.offsetTop=0;v.dispatchEvent(new Event('resize'));});await expect(page.locator('.shell')).toHaveAttribute('data-viewport-height','400');expect((await measure()).shell.height).toBe(400);}
  expect(errors).toEqual([]);
 }finally{await context.close()}
});






