import {test,expect,type WebSocketRoute} from '@playwright/test';
import type {Card,RoomView} from '../../shared/rules.js';
test('special cards UI: GET, every ROB card together, EXCHANGE offer and recipient reply',async({page})=>{
 const own:Card[]=[{id:'get',kind:'get2'},{id:'rob',kind:'rob'},{id:'ex',kind:'exchange'},{id:'shield',kind:'protect'},{id:'offer',kind:'pronoun'}];
 const player={id:'me',name:'나',avatar:'pronoun' as const,rating:1000,ratingDelta:0,points:0,reward:0,score:0,ready:true,connected:true,handCount:5,rematch:false,ai:false};
 const room:RoomView={code:'123456',phase:'battle',matchId:'special-ui',players:[player,{...player,id:'rival',name:'상대',handCount:2,lastPlayed:[{id:'target-field',kind:'article'}]},{...player,id:'third',name:'다른 상대',handCount:1}],you:'me',hand:own,handVersion:1,endsAt:0,stageEndsAt:0,nextDealAt:Date.now()+10000,dealSerial:1,deckCount:34,deckTotal:39,usedCards:[],dealIntervalMs:10000,goCount:0,multiplier:1,highScore:0,serverNow:Date.now(),actionAt:0,exchangeAt:0,reconnectMs:30000,durationMs:0,log:[],expiresAt:0};
 let ws:WebSocketRoute;const requests:any[]=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.routeWebSocket('**/socket',route=>{ws=route;route.onMessage(raw=>{const m=JSON.parse(String(raw));if(m.type==='hello'){route.send(JSON.stringify({type:'session',token:'special-ui',name:'나',avatar:'pronoun',rating:1000,points:0}));route.send(JSON.stringify({type:'state',room}));}else if(m.type==='inspectRob'){route.send(JSON.stringify({type:'robView',matchId:room.matchId,cardId:m.cardId,players:[{id:'rival',name:'상대',avatar:'pronoun',connected:true,handVersion:3,fieldVersion:4,cards:[{id:'forbidden-rob',kind:'rob',source:'hand'},{id:'forbidden-shield',kind:'protect',source:'hand'},{id:'target-verb',kind:'verb',source:'hand'},{id:'target-mass',kind:'mass',source:'hand'},{id:'target-field',kind:'article',source:'field'}]},{id:'third',name:'다른 상대',avatar:'adjective',connected:true,handVersion:2,fieldVersion:0,cards:[{id:'third-card',kind:'adjective',source:'hand'}]}]}));}else if(m.type==='inspectExchange'){route.send(JSON.stringify({type:'exchangeView',matchId:room.matchId,cardId:m.cardId,players:[{id:'rival',name:'상대',avatar:'pronoun',handVersion:3,cards:[{id:'forbidden-ex',kind:'exchange'},{id:'target-verb',kind:'verb'},{id:'target-mass',kind:'mass'}]}]}));}else if(m.type==='special'||m.type==='exchangeReply'){requests.push(m);route.send(JSON.stringify({type:'ack',requestId:m.requestId}));}});});
 await page.goto('/');await expect(page.locator('.hand .game-card')).toHaveCount(5);await page.getByRole('button',{name:'손패 펼쳐 보기'}).click();
 await page.locator('[data-card-id="shield"]').click();await expect(page.getByText('PROTECT는 손에 가지고 있으면 ROB을 자동으로 막아요.')).toBeVisible();
 await page.locator('[data-card-id="get"]').click();await expect.poll(()=>requests.length).toBe(1);expect(requests[0]).toMatchObject({type:'special',cardId:'get'});
 await page.locator('[data-card-id="rob"]').click();await expect(page.getByRole('dialog',{name:'ROB 카드 선택'})).toBeVisible();await expect(page.locator('.rob-card-choice')).toHaveCount(4);await expect(page.locator('.rob-card-owner').filter({hasText:/^상대의 카드$/})).toHaveCount(3);await expect(page.locator('.rob-card-owner').filter({hasText:/^다른 상대의 카드$/})).toHaveCount(1);await page.screenshot({path:'docs/screenshots/rob-all-cards.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('.rob-card-choice')).toHaveCount(4);await page.setViewportSize({width:1280,height:720});await page.getByRole('button',{name:'상대의 필드 정관사 카드 뺏기',exact:true}).click();await page.getByRole('button',{name:'사용하기'}).click();await expect.poll(()=>requests.length).toBe(2);expect(requests[1]).toMatchObject({type:'special',cardId:'rob',targetId:'rival',stealId:'target-field',stealSource:'field',targetFieldVersion:4});
 await page.locator('[data-card-id="ex"]').click();await expect(page.getByRole('heading',{name:'내 카드 선택하기'})).toBeVisible();await expect(page.getByRole('heading',{name:'상대 카드 선택하기'})).toBeVisible();await expect(page.locator('.exchange-column').first().locator('.exchange-cards button')).toHaveCount(2);await expect(page.getByRole('button',{name:'내 Protect 카드 선택'})).toHaveCount(0);await expect(page.getByRole('button',{name:'상대의 Exchange 카드 선택'})).toHaveCount(0);await page.getByRole('button',{name:'내 대명사 카드 선택'}).click();await page.getByRole('button',{name:'상대의 일반동사 카드 선택'}).click();await page.getByRole('button',{name:'교환 요청 보내기'}).click();await expect.poll(()=>requests.length).toBe(3);expect(requests[2]).toMatchObject({type:'special',cardId:'ex',targetId:'rival',offerId:'offer',wantedId:'target-verb',targetHandVersion:3});
 room.exchange={id:'exchange-ui',fromId:'rival',toId:'me',expiresAt:Date.now()+15000,offer:{id:'their-offer',kind:'verb'},wanted:{id:'offer',kind:'pronoun'}};ws!.send(JSON.stringify({type:'state',room}));await expect(page.getByRole('dialog',{name:'교환 요청 수락 또는 거절'})).toBeVisible();await expect(page.locator('.exchange-sender .character-avatar')).toHaveCount(1);expect(await page.locator('.exchange-pair .illustration').first().evaluate(el=>el.getBoundingClientRect().width)).toBeLessThanOrEqual(100);await page.getByRole('button',{name:'교환 수락'}).click();await expect.poll(()=>requests.length).toBe(4);expect(requests[3]).toMatchObject({type:'exchangeReply',exchangeId:'exchange-ui',accept:true});await page.getByRole('button',{name:'동사 필요'}).click();await expect.poll(()=>requests.length).toBe(5);expect(requests[4]).toMatchObject({type:'exchangeReply',accept:false,reason:'동사 필요'});expect(errors).toEqual([]);
});
test('AI test cheat and full-size card inspection are visible in battle',async({page})=>{
 const own:Card[]=[{id:'card-to-zoom',kind:'get2'}];
 const player={id:'me',name:'나',avatar:'pronoun' as const,rating:1000,ratingDelta:0,points:0,reward:0,score:0,ready:true,connected:true,handCount:1,rematch:false,ai:false};
 const room:RoomView={code:'123456',phase:'battle',matchId:'cheat-ui',players:[player,{...player,id:'bot',name:'AI',ai:true}],you:'me',hand:own,handVersion:1,endsAt:0,stageEndsAt:0,nextDealAt:Date.now()+10000,dealSerial:1,deckCount:38,deckTotal:39,usedCards:[],dealIntervalMs:10000,goCount:0,multiplier:1,highScore:0,serverNow:Date.now(),actionAt:0,exchangeAt:0,reconnectMs:30000,durationMs:0,log:[],expiresAt:0};
 const messages:any[]=[];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.routeWebSocket('**/socket',route=>{route.onMessage(raw=>{const msg=JSON.parse(String(raw));if(msg.type==='hello'){route.send(JSON.stringify({type:'session',token:'cheat-ui',name:'나',avatar:'pronoun',rating:1000,points:0}));route.send(JSON.stringify({type:'state',room}));}else if(msg.type==='debugSpecials'){messages.push(msg);route.send(JSON.stringify({type:'ack',requestId:msg.requestId}));room.testMode=true;route.send(JSON.stringify({type:'state',room}));}});});
 await page.goto('/');await page.getByRole('button',{name:'설정 열기'}).click();await page.getByRole('button',{name:'치트 · 특수카드 받기'}).click();await page.getByRole('button',{name:'설정 열기'}).click();await expect.poll(()=>messages.length).toBe(1);await expect(page.getByText('테스트 판 · 보상 없음')).toBeVisible();
 await expect.poll(()=>page.locator('[data-card-id="card-to-zoom"] .illustration').evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBe(488);
 await page.getByRole('button',{name:'카드 확대 보기'}).click();await page.locator('[data-card-id="card-to-zoom"]').click();await expect(page.getByRole('dialog',{name:'카드 확대 보기'})).toBeVisible();
 const size=await page.locator('.card-inspect-dialog .illustration').evaluate(el=>el.getBoundingClientRect().width);expect(size).toBeGreaterThan(300);
 await page.getByRole('button',{name:'카드 확대 닫기'}).click();await expect(page.getByRole('dialog',{name:'카드 확대 보기'})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await page.locator('[data-card-id="card-to-zoom"]').click();
 await expect(page.getByRole('dialog',{name:'카드 확대 보기'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});

